export interface SectorDetail {
  id: string;
  name: string;
  tagline: string;
  stabilityScore: number;
  infrastructure: number;
  aiDeployment: number;
  policyFramework: number;
  themeColor: string;
  gaps: { title: string; priority: 'Critical' | 'High Priority' | 'Medium Priority'; desc: string }[];
  opportunity: { summary: string; detail: string; readiness: string; competition: string; roi: string; tam: string };
  history: { month: string; deployments: number; investment: number; readiness: number }[];
}

export const SECTOR_DETAILS: Record<string, SectorDetail> = {
  healthcare: {
    id: 'healthcare',
    name: 'Healthcare',
    tagline: 'Comprehensive assessment of AI adoption, system stability, and opportunity gaps in global healthcare infrastructure.',
    stabilityScore: 62,
    infrastructure: 58,
    aiDeployment: 68,
    policyFramework: 59,
    themeColor: 'sector-healthcare',
    gaps: [
      { title: 'Rural Diagnostics Coverage', priority: 'High Priority', desc: 'Limited AI-powered diagnostic tools in rural and underserved regions.' },
      { title: 'Predictive Triage Systems', priority: 'Critical', desc: 'Emergency departments lack real-time AI triage capabilities.' },
      { title: 'AI Regulatory Clarity', priority: 'Medium Priority', desc: 'Inconsistent approval frameworks for medical AI systems across jurisdictions.' },
    ],
    opportunity: { summary: 'High system strain + moderate capital inflow = strong early-stage opportunity', detail: 'Healthcare presents a compelling entry point for AI infrastructure providers with clear use cases and measurable ROI potential.', readiness: 'Strong Demand', competition: 'Moderately Competitive', roi: '18-24 months', tam: '$84B by 2028' },
    history: [
      { month: 'Jan', deployments: 3200, investment: 18.2, readiness: 55 },
      { month: 'Feb', deployments: 3450, investment: 19.1, readiness: 56 },
      { month: 'Mar', deployments: 3800, investment: 19.8, readiness: 57 },
      { month: 'Apr', deployments: 4100, investment: 20.5, readiness: 58 },
      { month: 'May', deployments: 4600, investment: 21.3, readiness: 59 },
      { month: 'Jun', deployments: 5200, investment: 22.0, readiness: 60 },
      { month: 'Jul', deployments: 5800, investment: 22.8, readiness: 61 },
      { month: 'Aug', deployments: 6500, investment: 23.2, readiness: 61 },
      { month: 'Sep', deployments: 7200, investment: 23.8, readiness: 62 },
      { month: 'Oct', deployments: 8100, investment: 24.0, readiness: 62 },
      { month: 'Nov', deployments: 9000, investment: 24.3, readiness: 63 },
      { month: 'Dec', deployments: 9800, investment: 24.8, readiness: 64 },
    ],
  },
  education: {
    id: 'education',
    name: 'Education',
    tagline: 'Assessing AI readiness, learning platform maturity, and digital equity gaps across global education systems.',
    stabilityScore: 58,
    infrastructure: 52,
    aiDeployment: 64,
    policyFramework: 48,
    themeColor: 'sector-education',
    gaps: [
      { title: 'Digital Equity Access', priority: 'Critical', desc: 'Over 40% of students in developing nations lack access to AI-enhanced learning platforms.' },
      { title: 'Teacher AI Training', priority: 'High Priority', desc: 'Less than 20% of educators globally trained on AI-assisted teaching tools.' },
      { title: 'Curriculum Standardization', priority: 'Medium Priority', desc: 'No international framework for integrating AI literacy into K-12 curricula.' },
    ],
    opportunity: { summary: 'Massive unmet demand + low capital = emerging greenfield opportunity', detail: 'Education AI is pre-inflection. Early movers building accessible, localized platforms can capture outsized market share.', readiness: 'High Demand', competition: 'Low Competition', roi: '24-36 months', tam: '$62B by 2029' },
    history: [
      { month: 'Jan', deployments: 2100, investment: 8.5, readiness: 48 },
      { month: 'Feb', deployments: 2300, investment: 9.0, readiness: 49 },
      { month: 'Mar', deployments: 2600, investment: 9.4, readiness: 50 },
      { month: 'Apr', deployments: 2900, investment: 9.8, readiness: 51 },
      { month: 'May', deployments: 3300, investment: 10.2, readiness: 52 },
      { month: 'Jun', deployments: 3800, investment: 10.8, readiness: 53 },
      { month: 'Jul', deployments: 4200, investment: 11.1, readiness: 54 },
      { month: 'Aug', deployments: 4700, investment: 11.5, readiness: 55 },
      { month: 'Sep', deployments: 5200, investment: 11.8, readiness: 56 },
      { month: 'Oct', deployments: 5800, investment: 12.1, readiness: 57 },
      { month: 'Nov', deployments: 6400, investment: 12.4, readiness: 57 },
      { month: 'Dec', deployments: 7100, investment: 12.8, readiness: 58 },
    ],
  },
  energy: {
    id: 'energy',
    name: 'Energy & Climate',
    tagline: 'Evaluating smart grid deployment, climate AI readiness, and clean energy transition intelligence across energy infrastructure.',
    stabilityScore: 48,
    infrastructure: 42,
    aiDeployment: 54,
    policyFramework: 44,
    themeColor: 'sector-energy',
    gaps: [
      { title: 'Grid Modernization', priority: 'Critical', desc: 'Over 60% of global power grids lack AI-enabled predictive maintenance and load balancing.' },
      { title: 'Climate Modeling Access', priority: 'High Priority', desc: 'Advanced climate AI models remain concentrated in a handful of institutions and nations.' },
      { title: 'Renewable Forecasting', priority: 'High Priority', desc: 'AI-driven renewable energy output prediction deployed in less than 25% of solar/wind facilities.' },
    ],
    opportunity: { summary: 'Critical urgency + high capital = competitive but high-reward sector', detail: 'Energy is the highest-urgency sector. Government mandates and climate deadlines create a forcing function for rapid AI adoption.', readiness: 'Very Strong Demand', competition: 'Highly Competitive', roi: '12-18 months', tam: '$97B by 2028' },
    history: [
      { month: 'Jan', deployments: 1800, investment: 14.2, readiness: 38 },
      { month: 'Feb', deployments: 2000, investment: 14.8, readiness: 39 },
      { month: 'Mar', deployments: 2300, investment: 15.5, readiness: 40 },
      { month: 'Apr', deployments: 2700, investment: 16.1, readiness: 41 },
      { month: 'May', deployments: 3100, investment: 16.8, readiness: 42 },
      { month: 'Jun', deployments: 3600, investment: 17.2, readiness: 43 },
      { month: 'Jul', deployments: 4100, investment: 17.6, readiness: 44 },
      { month: 'Aug', deployments: 4700, investment: 18.0, readiness: 45 },
      { month: 'Sep', deployments: 5300, investment: 18.3, readiness: 46 },
      { month: 'Oct', deployments: 6000, investment: 18.5, readiness: 47 },
      { month: 'Nov', deployments: 6800, investment: 18.7, readiness: 47 },
      { month: 'Dec', deployments: 7600, investment: 19.0, readiness: 48 },
    ],
  },
  agriculture: {
    id: 'agriculture',
    name: 'Agriculture',
    tagline: 'Mapping precision farming adoption, food security AI solutions, and smart agriculture deployment across global food systems.',
    stabilityScore: 54,
    infrastructure: 46,
    aiDeployment: 52,
    policyFramework: 40,
    themeColor: 'sector-agriculture',
    gaps: [
      { title: 'Smallholder Access', priority: 'Critical', desc: 'AI-powered precision agriculture tools reach less than 5% of smallholder farmers globally.' },
      { title: 'Supply Chain Intelligence', priority: 'High Priority', desc: 'Food supply chain AI monitoring covers only 18% of global distribution networks.' },
      { title: 'Soil & Water Monitoring', priority: 'Medium Priority', desc: 'Sensor-based AI soil health and irrigation systems deployed on less than 12% of arable land.' },
    ],
    opportunity: { summary: 'High urgency + low capital = emerging opportunity with impact potential', detail: 'Agriculture AI is drastically under-invested relative to its importance. Solutions addressing food security have strong NGO/government funding pathways.', readiness: 'Moderate Demand', competition: 'Low Competition', roi: '24-36 months', tam: '$42B by 2029' },
    history: [
      { month: 'Jan', deployments: 1200, investment: 5.8, readiness: 42 },
      { month: 'Feb', deployments: 1350, investment: 6.1, readiness: 43 },
      { month: 'Mar', deployments: 1500, investment: 6.4, readiness: 44 },
      { month: 'Apr', deployments: 1700, investment: 6.8, readiness: 45 },
      { month: 'May', deployments: 1950, investment: 7.1, readiness: 46 },
      { month: 'Jun', deployments: 2200, investment: 7.4, readiness: 47 },
      { month: 'Jul', deployments: 2500, investment: 7.7, readiness: 48 },
      { month: 'Aug', deployments: 2850, investment: 7.9, readiness: 49 },
      { month: 'Sep', deployments: 3200, investment: 8.1, readiness: 50 },
      { month: 'Oct', deployments: 3600, investment: 8.2, readiness: 51 },
      { month: 'Nov', deployments: 4000, investment: 8.4, readiness: 52 },
      { month: 'Dec', deployments: 4500, investment: 8.6, readiness: 54 },
    ],
  },
  labor: {
    id: 'labor',
    name: 'Labor & Economy',
    tagline: 'Tracking workforce displacement, reskilling readiness, and economic AI integration across global labor markets.',
    stabilityScore: 51,
    infrastructure: 48,
    aiDeployment: 45,
    policyFramework: 38,
    themeColor: 'sector-labor',
    gaps: [
      { title: 'Workforce Reskilling', priority: 'Critical', desc: 'Only 12% of displaced workers have access to AI-focused reskilling programs.' },
      { title: 'Job Displacement Monitoring', priority: 'High Priority', desc: 'Real-time AI job displacement tracking systems exist in fewer than 10 countries.' },
      { title: 'Gig Economy Protections', priority: 'Medium Priority', desc: 'AI-driven gig platforms lack standardized worker protection frameworks in most jurisdictions.' },
    ],
    opportunity: { summary: 'Medium urgency + medium capital = emerging with policy-driven growth', detail: 'Labor AI tools for reskilling and workforce analytics are gaining traction as governments mandate transition support.', readiness: 'Growing Demand', competition: 'Moderate Competition', roi: '18-30 months', tam: '$38B by 2029' },
    history: [
      { month: 'Jan', deployments: 1500, investment: 7.2, readiness: 40 },
      { month: 'Feb', deployments: 1650, investment: 7.5, readiness: 41 },
      { month: 'Mar', deployments: 1800, investment: 7.8, readiness: 42 },
      { month: 'Apr', deployments: 2000, investment: 8.1, readiness: 43 },
      { month: 'May', deployments: 2250, investment: 8.4, readiness: 44 },
      { month: 'Jun', deployments: 2500, investment: 8.7, readiness: 45 },
      { month: 'Jul', deployments: 2800, investment: 9.0, readiness: 46 },
      { month: 'Aug', deployments: 3100, investment: 9.2, readiness: 47 },
      { month: 'Sep', deployments: 3450, investment: 9.5, readiness: 48 },
      { month: 'Oct', deployments: 3800, investment: 9.7, readiness: 49 },
      { month: 'Nov', deployments: 4200, investment: 9.9, readiness: 50 },
      { month: 'Dec', deployments: 4600, investment: 10.1, readiness: 51 },
    ],
  },
  governance: {
    id: 'governance',
    name: 'Governance',
    tagline: 'Assessing AI policy readiness, digital governance frameworks, and public sector automation across government systems.',
    stabilityScore: 44,
    infrastructure: 38,
    aiDeployment: 41,
    policyFramework: 52,
    themeColor: 'sector-governance',
    gaps: [
      { title: 'AI Policy Frameworks', priority: 'Critical', desc: 'Fewer than 30 countries have comprehensive AI governance legislation in force.' },
      { title: 'Public Service Automation', priority: 'High Priority', desc: 'Government service delivery AI adoption below 15% globally, creating massive efficiency gaps.' },
      { title: 'Algorithmic Accountability', priority: 'High Priority', desc: 'Audit mechanisms for government AI decision-making exist in fewer than 12 jurisdictions.' },
    ],
    opportunity: { summary: 'High urgency + low capital = strong opportunity for GovTech AI', detail: 'Governments are under pressure to modernize. First movers in GovTech AI with compliance built-in will capture long-term contracts.', readiness: 'Strong Demand', competition: 'Low Competition', roi: '24-48 months', tam: '$56B by 2030' },
    history: [
      { month: 'Jan', deployments: 800, investment: 4.2, readiness: 34 },
      { month: 'Feb', deployments: 900, investment: 4.5, readiness: 35 },
      { month: 'Mar', deployments: 1050, investment: 4.8, readiness: 36 },
      { month: 'Apr', deployments: 1200, investment: 5.1, readiness: 37 },
      { month: 'May', deployments: 1400, investment: 5.4, readiness: 38 },
      { month: 'Jun', deployments: 1600, investment: 5.7, readiness: 39 },
      { month: 'Jul', deployments: 1850, investment: 5.9, readiness: 40 },
      { month: 'Aug', deployments: 2100, investment: 6.1, readiness: 41 },
      { month: 'Sep', deployments: 2400, investment: 6.3, readiness: 42 },
      { month: 'Oct', deployments: 2700, investment: 6.5, readiness: 42 },
      { month: 'Nov', deployments: 3050, investment: 6.7, readiness: 43 },
      { month: 'Dec', deployments: 3400, investment: 6.9, readiness: 44 },
    ],
  },
};
